version: "3"

services: 
  web:
    build: .
    env_file:
      - .env
    #enviroment:
    #  - MONGO_NAME=apimongo
    depends_on:
      - db
    ports:
     - "8000:3000"
    volumes:
     - .:/usr/src/app
     - /usr/src/app/node_modules
  db:
    image: mongo
    restart: always
    expose:
      - "27017"
    volumes:
     - mongodata:/data/db
volumes:
  mongodata: